theme = "doom_acario_dark"

[editor]
true-color = true
line-number = "relative"
mouse = true
bufferline = "always"
auto-completion = true
auto-format = true
auto-save = true
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints	= true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.statusline]
left = ["spinner", "mode", "file-type", "file-encoding", "diagnostics"]
center = ["version-control", "file-name", "read-only-indicator", "position-percentage"]
right = ["selections", "register", "position"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

