import = ["/home/ivan/.config/alacritty/themes/blood_moon.toml"]
live_config_reload = true
#save_to_clipboard = true
#"window.dynamic_title" = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12
offset = { x = 0, y = 0 }

[font.bold]
family = "JetBrains Mono Nerd Font"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"

[font.italic]
family = "JetBrains Mono Nerd Font"

[font.normal]
family = "JetBrains Mono Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.98
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30
