theme = "doom_acario_dark"
#theme = "heisenberg"

[editor]
line-number = "absolute"
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-type", "file-encoding", "position-percentage"]
center = ["file-name", "diagnostics"]

[keys.normal]
#C-tab = ":buffer-next"

[keys.insert]
#"C-tab" = ":buffer-next"