theme = "doom_acario_dark"

[editor]
line-number = "absolute"
mouse = true
bufferline = "always"
#gutters = ["diagnostics"]
auto-completion = true
auto-format = true
auto-save = true
auto-info = true
#rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["spinner", "mode", "file-type", "file-encoding", "diagnostics"]
center = ["version-control", "file-name", "read-only-indicator", "position-percentage"]
right = ["selections", "register", "position"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
