[[language]]
name = "bash"
auto-format = true

[[language]]
name = "java"
auto-format = true

[[language]]
name = "nix"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "rust"
auto-format = true
